### PR TITLE
Adjust set(..) and get(..) in UnsafeBitArray.scala such that all bits are potentially used.

### PR DESCRIPTION
**Pull request by cmarxer**
(1) Adjust set(..) and get(..) in UnsafeBitArray.scala such that all bits are potentially used.

Up to now, only the first (indices+7) bytes were used. Example: If numberOfBits is 192 then indices is 3. In this case, only the first 10 of 24 bytes are potentially touched. The remaining 14 bytes stay always 0x00.

(2) Serialization/Dumping

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
I picked 474ac7e59ebd014d1d906959f6fa4697402884c0 and published 0.4.2. Thank you!!
I'm not sure about serialization yet.

**Comment by cmarxer** [comment]
Thanks for merging!

Btw, the README should be updated to:
`libraryDependencies += "com.github.alexandrnikitin" %% "bloom-filter" % "0.4.2"`

**Comment by cmarxer** [comment]
In case you are interested in De/serialization: Complementary to serialize() there is now also a restoreArray() method in this branch. It allows to add all elements dumped with serialize() to another bloom filter. Already existing entries are not preserved.

**Comment by velvia** [comment]
+1 for these methods.  These would satisfy our needs to be honest.

The only thing is that a user might want to also save the other parameters (number of bits etc) to properly create the instance right?

**Comment by alexandrnikitin** [comment]
@cmarxer Thank you for your PR. I decided to go with `Output/InputStream` because this BF intended to support huge amount of memory which won't fit into array of bytes. Also the Stream approach is more flexible in terms of performance and doesn't allocate the same chunk of memory just to serialize it.

**Comment by cmarxer** [comment]
Thanks! That also fits my needs!

**Pull request closed without merging**
